# Generated by Django 3.0.5 on 2020-05-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_item', '0004_auto_20200509_1315'),
        ('list_item', '0002_auto_20200505_1209'),
    ]

    operations = [
    ]
